configfile: "steps.yml" 
rule all:
    input:
        "results/helloworld_output.txt"  #Final output 

rule prepare_data:
    output:
        "data/input.txt"
    conda:
        "environment.yml"
    shell:
        """
        mkdir -p data                         
        echo "Hello World!" > {output} 
        """

rule run_example:
    input:
        "data/input.txt"
    conda:
        "environment.yml"
    output:
        "results/example_output.txt"
    shell:
        """
        mkdir -p results    
        cat {input} > {output} 
        """

rule output_results:
    input:
        "results/example_output.txt"
    output:
        "results/helloworld_output.txt"
    conda:
        "environment.yml"
    shell:
        """ 
        cp {input} {output}  
        """
