name: Snakemake-reana-helloworld-example
channels:
  - conda-forge
dependencies:
  - python=3.10
  - bioconda::snakemake=7.25.0
  - pip
  - pytest
  - pandas
  - samtools
  - matplotlib
  - ruff
  - singularity
  - pip:
    - reana-client