#This is the yadage workflow hello_world but in Snakemake:
configfile: "steps.yml"

rule all:
    input:
        "results/helloworld_output.txt"  #this is a final output 

rule prepare_data:
    output:
        "data/input.txt"
    shell:
        """
        mkdir -p data                         
        echo "Hello, World!" > {output} 
        """

rule run_example:
    input:
        "data/input.txt"
    output:
        "results/example_output.txt"
    shell:
        """
        mkdir -p results    
        cat {input} > {output} 
        """

rule output_results:
    input:
        "results/example_output.txt"
    output:
        "results/helloworld_output.txt"
    shell:
        """ 
        cp {input} {output}  
        """
