name: Snakemake CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

defaults: 
  run:
    shell: bash -l {0}

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:

      - name: Clone repository
        uses: actions/checkout@v3    

      - name: Install micromamba and create environment
        uses: mamba-org/setup-micromamba@v1
        with: 
          environment-file: recast_helloworld/environment.yml

      - name: List installed environment dependencies 
        run: | 
          micromamba list

      - name: Linting
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.test'
          snakefile: 'workflow/Snakefile'

      - name: Testing
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.test'
          snakefile: 'workflow/Snakefile'
          args: '--cores 1 --use-conda --conda-cleanup-pkgs cache'

      - name: Create container file
        uses: snakemake/snakemake-github-action@v1
        with:
          snakefile: 'workflow/Snakefile'
          task: 'containerize'
